platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
project 'LionheartAlamofireClient.xcodeproj'

inhibit_all_warnings!
use_frameworks!

target 'LionheartAlamofireClient_Example' do
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
  pod 'LionheartAlamofireClient', :path => '../'

  target 'LionheartAlamofireClient_Tests' do
    pod 'Quick', :git => 'git@github.com:Quick/Quick.git', :branch => "swift-3.0"
    pod 'Nimble', :git => 'git@github.com:Quick/Nimble.git', :branch => "swift-3.0"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
