author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/LionheartAlamofireClient"
github_file_prefix: "https://github.com/lionheart/LionheartAlamofireClient/tree/2.2.2"
xcodebuild_arguments: ["-workspace", "Example/LionheartAlamofireClient.xcworkspace", "-scheme", "LionheartAlamofireClient"]
readme: "README.md"
copyright: "&copy; 2016-2018 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"
use_safe_filenames: true

